import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Holy Bible</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
      <div className={styles.flex}>
            <Image
              src="/Jesus-color-silhouette-low-poly-pattern.svg"
              height={100}
              width={100}
              className="mt-10"
              objectFit="cover"
              alt="Jesus Logo"
            />
  <a className={styles.code} href="https://the-holy-bible.vercel.app">
    Home
  </a>
            <button className={styles.code}>
                DONATE
            </button>
        </div>
        <div>
          <nav className={styles.nav}>
              <ul>
            
                <a href="https://matthew-coral.vercel.app/">
                  <li>
                    Matthew
                  </li>
                </a>
                <a href="https://mark-alpha.vercel.app/">
                  <li>
                    Mark
                  </li>
                </a>
                <a href="https://luke-three.vercel.app/">
                <li>
                  Luke
                </li>
                </a>
                <a href="https://john-zeta.vercel.app/">
                <li>
                  John
                </li>
                </a>
              </ul>

          </nav>
        </div>
      </header>

      <main className={styles.main}>
      
       <h2>The Holy Bible's</h2>
        <h1 className={styles.title}>
            <a href="https://en.wikipedia.org/wiki/Bible">Index</a>
        </h1>
  
        <p className={styles.description}>
          
          <code className={styles.publisher}>&darr; Scroll &darr;</code>
        </p>

        <p className={styles.h2}>
        <span className={styles.span}> &darr; Romans 1:16 &rarr; </span>
          For I am not ashamed of the  gospel, because it is the power
          of God that brings salvation to everyone who believes. First the Jew & then the Gentile
        </p>
      <ol className={styles.index}>
       <a href="https://matthew-coral.vercel.app/">
        <li>
        Matthew
        </li>
        </a>
       <a href="https://mark-alpha.vercel.app/">
        <li>
        Mark
        </li>
        </a>
        <a href="https://luke-three.vercel.app/">
        <li>
        Luke
        </li>
        </a>

        <a href="https://john-zeta.vercel.app/">
        <li>
          John
        </li>
        </a>
        <a href="https://acts-zeta.vercel.app/">
        <li>
        Acts
        </li>
        </a>
        <a href="https://romans-five.vercel.app/">
        <li>
        Romans
        </li>
        </a>
        <a href="#">
        <li>
        1 Corinthians
        </li>
        </a>
        <a href="https://proverbs.vercel.app/">
        <li>
          Proverbs
        </li>
        </a>
      </ol>
        <code className={styles.code}> THE TRUE LIGHT WHO GIVES LIGHT TO EVERY MAN WAS COMING INTO THE WORLD. </code>
      
       
      

        <p className={styles.description}> 
        <code className={styles.publisher}>
        Coded, Published & Deployed by His servant: Jason Daniel Nutt 
        </code>
        </p>
      </main>

      <footer className={styles.footer}>
  
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
