import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Holy Bible</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
   
        <div>
          <nav className={styles.nav}>
              <ul>
            
                <a href="https://matthew-coral.vercel.app/">
                  <li>
                    Matthew
                  </li>
                </a>
                <a href="https://mark-alpha.vercel.app/">
                  <li>
                    Mark
                  </li>
                </a>
                <a href="https://luke-three.vercel.app/">
                <li>
                  Luke
                </li>
                </a>
                <a href="https://john-zeta.vercel.app/">
                <li>
                  John
                </li>
                </a>
              </ul>

          </nav>
        </div>
      </header>

      <main className={styles.main}>
      
       <h2>The Holy Bible</h2>
        <h1 className={styles.title}>
            <a href="https://en.wikipedia.org/wiki/Bible">Index</a>
        </h1>
        <div className={styles.flex}>
        <button className={styles.code}>
                    <a   href="https://the-holy-bible.vercel.app/">
                          HOME
                          </a>
                      </button>

          <a className={styles.code} href="https://www.linkedin.com/in/jnuttlovedisciple/">PUBLISHER</a>
                     
                     
                      
                  </div>
       
        <p className={styles.description}>
          
          <code className={styles.publisher}>&darr; Scroll &darr;</code>
        </p>

        <p className={styles.h2}>
        <span className={styles.span}> &darr; Romans 1:16 &rarr; </span>
          For I am not ashamed of the  gospel, because it is the power
          of God that brings salvation to everyone who believes. First the Jew & then the Gentile
        </p>
        <div>
                  <ul className={styles.grid}> 
                  <a href="https://matthew-coral.vercel.app/">
                    <li className={styles.li-1}>
                    Matthew
                    </li>
                    </a>
                  <a href="https://mark-alpha.vercel.app/">
                    <li className={styles.li-2}>
                    Mark
                    </li>
                    </a>
                    <a href="https://luke-three.vercel.app/">
                    <li className={styles.li-3}>
                    Luke
                    </li>
                    </a>

                    <a href="https://john-zeta.vercel.app/">
                    <li className={styles.li-4}>
                      John
                    </li>
                    </a>
                    <a href="https://acts-zeta.vercel.app/">
                    <li className={styles.li-5}>
                    Acts
                    </li>
                    
                   
                    </a>
                    </ul>
                    <ul className={styles.grid}>
                    <a href="https://romans-five.vercel.app/">
                    <li className={styles.li-6}>
                    Romans
                    </li>
                    </a>
                    <a href="https://first-corinthians.vercel.app/">
                    <li className={styles.li-7}>
                    1 Corinth
                    </li>
                    </a>
                    <a href="https://second-corinthians.vercel.app/">
                    <li className={styles.li-8}>
                    2 Corinth
                    </li>
                    </a>
                    <a href="https://galatians.vercel.app/">
                    <li className={styles.li-9}>
                    Galatians
                    </li>

                    </a>  

                    <a href="">
                    <li className={styles.li-10}>
                      Ephesians
                    </li>
                    </a>
                    </ul>

                    <ul className={styles.grid}> 
                  <a href="">
                    <li className={styles.li-1}>
                    Philippians
                    </li>
                    </a>
                  <a href="">
                    <li className={styles.li-2}>
                    Colossians
                    </li>
                    </a>
                    <a href="">
                    <li className={styles.li-3}>
                    1 Thessalonians
                    </li>
                    </a>

                    <a href="">
                    <li className={styles.li-4}>
                      2 Thessalonians
                    </li>
                    </a>
                   
                    </ul>

<ul className={styles.grid}>
                    <a href="">
                    <li className={styles.li-5}>
                    1 Timothy
                    </li>
                     </a>

                     <a href="">
                    <li className={styles.li-1}>
                    2 Timothy
                    </li>
                    </a>
                  <a href="">
                    <li className={styles.li-2}>
                    Titus
                    </li>
                    </a>
                    <a href="">
                    <li className={styles.li-3}>
                    Philemon
                    </li>
                    </a>

                    <a href="">
                    <li className={styles.li-4}>
                      Hebrews
                    </li>
                    </a>
</ul>

<ul className={styles.grid}>
                    <a href="">
                    <li className={styles.li-5}>
                    James
                    </li>
                     </a>

                     <a href="">
                    <li className={styles.li-1}>
                    1 Peter
                    </li>
                    </a>
                  <a href="">
                    <li className={styles.li-2}>
                    2 Peter
                    </li>
                    </a>
                    <a href="">
                    <li className={styles.li-3}>
                    1 John
                    </li>
                    </a>

                  
</ul>

<ul className={styles.grid}>
<a href="">
                    <li className={styles.li-4}>
                      2 John
                    </li>
                    </a>

                     <a href="">
                    <li className={styles.li-1}>
                    3 John
                    </li>
                    </a>
                  <a href="">
                    <li className={styles.li-2}>
                    Jude
                    </li>
                    </a>
                    <a href="">
                    <li className={styles.li-3}>
                    The Revelation of Jesus Christ
                    </li>
                    </a>

                    
</ul>


    </div>
        <div className={styles.h2}> THE TRUE LIGHT WHO GIVES LIGHT TO EVERY MAN WAS COMING INTO THE WORLD. </div>
      
       
      

        <p className={styles.description}> 
        <code className={styles.publisher}>
        Coded, Published & Deployed by His servant: Jason Daniel Nutt 
        </code>
        </p>
      </main>

      <footer className={styles.footer}>
  
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
